### PR TITLE
chore: [IOPLT-1727] Fix local environment for example app

### PR DESCRIPTION
**Pull request by dmnplb**
## Short description
Fix local environment for example app.

## List of changes proposed in this pull request
- Update `.ruby-version` to avoid generating a different `Podfile.lock`
- Update `Podfile` to avoid failed build with XCode 26.4 and above

### CODE REVIEW

File: example/ios/Podfile [hunk 1]
```diff
@@ -31,4 +31,21 @@ target 'ExampleApp' do
       # :ccache_enabled => true
     )
   end
-end
+
+  # Workaround for fmt compilation error with Xcode 26.4 / newer Apple Clang
+  # https://github.com/expo/expo/issues/44229
```
Comment (LeleDallas) [inline example/ios/Podfile:36]: It may be helpful to include a TODO indicating that this code should be removed once the related PR introduces a proper solution.
What do you think?

Comment (dmnplb) [reply example/ios/Podfile:36]: I added a simple TODO, nothing very detailed, but at least it signals that it's a temporary hack

**Review by LeleDallas — APPROVED** [review]
I was able to run the app with Xcode 26.4!
What do you think to apply the same workaround to the IO App?

**Comment by dmnplb** [comment]
> What do you think to apply the same workaround to the IO App?

I'm already using it locally, but given the number of contributors to the main app, I'm less keen to add it.
